server:
  port: 10021
spring:
  profiles:
    active: dev

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:8800'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
