server:
  port: 10009
swagger:
  title: SBT-Admin Docs
  group-name: sbt-admin
  description: SBT 后台管理服务Api文档
  version: 0.0.1
  license: Powered By SBT
  licenseUrl: http://www.micolore.cn/
  terms-of-service-url: http://www.micolore.cn/
  contact:
    name: micolore
    email: micolore@gmail.com
    url: https://github.com/micolore
  authorization:
    name: SBT OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://localhost:8080/oauth/token
  aggregator:
    provider-resources:
      - {name: sbt-seagger-api,  url: http://localhost:9090/v2/api-docs, swagger-version: 2.0}
